/*
WorldCat Search API v. 2

Testing MemberSharedPrintHoldingsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    openapiclient "github.com/catleeball/worldcat-api-client-go"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
)

func Test_openapi_MemberSharedPrintHoldingsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test MemberSharedPrintHoldingsApiService FindBibRetainedHoldings", func(t *testing.T) {

        t.Skip("skip test") // remove to run test

        resp, httpRes, err := apiClient.MemberSharedPrintHoldingsApi.FindBibRetainedHoldings(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
