/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchBibs200ResponseBibRecordsInnerWork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBibs200ResponseBibRecordsInnerWork{}

// SearchBibs200ResponseBibRecordsInnerWork struct for SearchBibs200ResponseBibRecordsInnerWork
type SearchBibs200ResponseBibRecordsInnerWork struct {
	// Id of the workset [Admin/Work/ID]
	Id *string `json:"id,omitempty"`
	// Number of items in Workset [Admin/Work/Count]
	Count *int32 `json:"count,omitempty"`
	// Items in Article Workset [WorkSet/NO]
	ArticleCluster []SearchBibs200ResponseBibRecordsInnerWorkArticleClusterInner `json:"articleCluster,omitempty"`
}

// NewSearchBibs200ResponseBibRecordsInnerWork instantiates a new SearchBibs200ResponseBibRecordsInnerWork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBibs200ResponseBibRecordsInnerWork() *SearchBibs200ResponseBibRecordsInnerWork {
	this := SearchBibs200ResponseBibRecordsInnerWork{}
	return &this
}

// NewSearchBibs200ResponseBibRecordsInnerWorkWithDefaults instantiates a new SearchBibs200ResponseBibRecordsInnerWork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBibs200ResponseBibRecordsInnerWorkWithDefaults() *SearchBibs200ResponseBibRecordsInnerWork {
	this := SearchBibs200ResponseBibRecordsInnerWork{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerWork) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerWork) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerWork) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SearchBibs200ResponseBibRecordsInnerWork) SetId(v string) {
	o.Id = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerWork) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerWork) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerWork) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SearchBibs200ResponseBibRecordsInnerWork) SetCount(v int32) {
	o.Count = &v
}

// GetArticleCluster returns the ArticleCluster field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerWork) GetArticleCluster() []SearchBibs200ResponseBibRecordsInnerWorkArticleClusterInner {
	if o == nil || IsNil(o.ArticleCluster) {
		var ret []SearchBibs200ResponseBibRecordsInnerWorkArticleClusterInner
		return ret
	}
	return o.ArticleCluster
}

// GetArticleClusterOk returns a tuple with the ArticleCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerWork) GetArticleClusterOk() ([]SearchBibs200ResponseBibRecordsInnerWorkArticleClusterInner, bool) {
	if o == nil || IsNil(o.ArticleCluster) {
		return nil, false
	}
	return o.ArticleCluster, true
}

// HasArticleCluster returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerWork) HasArticleCluster() bool {
	if o != nil && !IsNil(o.ArticleCluster) {
		return true
	}

	return false
}

// SetArticleCluster gets a reference to the given []SearchBibs200ResponseBibRecordsInnerWorkArticleClusterInner and assigns it to the ArticleCluster field.
func (o *SearchBibs200ResponseBibRecordsInnerWork) SetArticleCluster(v []SearchBibs200ResponseBibRecordsInnerWorkArticleClusterInner) {
	o.ArticleCluster = v
}

func (o SearchBibs200ResponseBibRecordsInnerWork) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBibs200ResponseBibRecordsInnerWork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.ArticleCluster) {
		toSerialize["articleCluster"] = o.ArticleCluster
	}
	return toSerialize, nil
}

type NullableSearchBibs200ResponseBibRecordsInnerWork struct {
	value *SearchBibs200ResponseBibRecordsInnerWork
	isSet bool
}

func (v NullableSearchBibs200ResponseBibRecordsInnerWork) Get() *SearchBibs200ResponseBibRecordsInnerWork {
	return v.value
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerWork) Set(val *SearchBibs200ResponseBibRecordsInnerWork) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBibs200ResponseBibRecordsInnerWork) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerWork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBibs200ResponseBibRecordsInnerWork(val *SearchBibs200ResponseBibRecordsInnerWork) *NullableSearchBibs200ResponseBibRecordsInnerWork {
	return &NullableSearchBibs200ResponseBibRecordsInnerWork{value: val, isSet: true}
}

func (v NullableSearchBibs200ResponseBibRecordsInnerWork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerWork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
