/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchBibs200ResponseBibRecordsInnerClassification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBibs200ResponseBibRecordsInnerClassification{}

// SearchBibs200ResponseBibRecordsInnerClassification struct for SearchBibs200ResponseBibRecordsInnerClassification
type SearchBibs200ResponseBibRecordsInnerClassification struct {
	// Dewey Decimal Classification Number [v082sa,b]
	Dewey *string `json:"dewey,omitempty"`
	// Library of Congress Call Number [v050sa,b]
	Lc *string `json:"lc,omitempty"`
	// National Library of Medicine Call Number [v060sa,b]
	Nlm *string `json:"nlm,omitempty"`
	// Government Doc number [v086sa]
	GovDoc []string `json:"govDoc,omitempty"`
}

// NewSearchBibs200ResponseBibRecordsInnerClassification instantiates a new SearchBibs200ResponseBibRecordsInnerClassification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBibs200ResponseBibRecordsInnerClassification() *SearchBibs200ResponseBibRecordsInnerClassification {
	this := SearchBibs200ResponseBibRecordsInnerClassification{}
	return &this
}

// NewSearchBibs200ResponseBibRecordsInnerClassificationWithDefaults instantiates a new SearchBibs200ResponseBibRecordsInnerClassification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBibs200ResponseBibRecordsInnerClassificationWithDefaults() *SearchBibs200ResponseBibRecordsInnerClassification {
	this := SearchBibs200ResponseBibRecordsInnerClassification{}
	return &this
}

// GetDewey returns the Dewey field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetDewey() string {
	if o == nil || IsNil(o.Dewey) {
		var ret string
		return ret
	}
	return *o.Dewey
}

// GetDeweyOk returns a tuple with the Dewey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetDeweyOk() (*string, bool) {
	if o == nil || IsNil(o.Dewey) {
		return nil, false
	}
	return o.Dewey, true
}

// HasDewey returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) HasDewey() bool {
	if o != nil && !IsNil(o.Dewey) {
		return true
	}

	return false
}

// SetDewey gets a reference to the given string and assigns it to the Dewey field.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) SetDewey(v string) {
	o.Dewey = &v
}

// GetLc returns the Lc field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetLc() string {
	if o == nil || IsNil(o.Lc) {
		var ret string
		return ret
	}
	return *o.Lc
}

// GetLcOk returns a tuple with the Lc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetLcOk() (*string, bool) {
	if o == nil || IsNil(o.Lc) {
		return nil, false
	}
	return o.Lc, true
}

// HasLc returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) HasLc() bool {
	if o != nil && !IsNil(o.Lc) {
		return true
	}

	return false
}

// SetLc gets a reference to the given string and assigns it to the Lc field.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) SetLc(v string) {
	o.Lc = &v
}

// GetNlm returns the Nlm field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetNlm() string {
	if o == nil || IsNil(o.Nlm) {
		var ret string
		return ret
	}
	return *o.Nlm
}

// GetNlmOk returns a tuple with the Nlm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetNlmOk() (*string, bool) {
	if o == nil || IsNil(o.Nlm) {
		return nil, false
	}
	return o.Nlm, true
}

// HasNlm returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) HasNlm() bool {
	if o != nil && !IsNil(o.Nlm) {
		return true
	}

	return false
}

// SetNlm gets a reference to the given string and assigns it to the Nlm field.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) SetNlm(v string) {
	o.Nlm = &v
}

// GetGovDoc returns the GovDoc field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetGovDoc() []string {
	if o == nil || IsNil(o.GovDoc) {
		var ret []string
		return ret
	}
	return o.GovDoc
}

// GetGovDocOk returns a tuple with the GovDoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) GetGovDocOk() ([]string, bool) {
	if o == nil || IsNil(o.GovDoc) {
		return nil, false
	}
	return o.GovDoc, true
}

// HasGovDoc returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) HasGovDoc() bool {
	if o != nil && !IsNil(o.GovDoc) {
		return true
	}

	return false
}

// SetGovDoc gets a reference to the given []string and assigns it to the GovDoc field.
func (o *SearchBibs200ResponseBibRecordsInnerClassification) SetGovDoc(v []string) {
	o.GovDoc = v
}

func (o SearchBibs200ResponseBibRecordsInnerClassification) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBibs200ResponseBibRecordsInnerClassification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dewey) {
		toSerialize["dewey"] = o.Dewey
	}
	if !IsNil(o.Lc) {
		toSerialize["lc"] = o.Lc
	}
	if !IsNil(o.Nlm) {
		toSerialize["nlm"] = o.Nlm
	}
	if !IsNil(o.GovDoc) {
		toSerialize["govDoc"] = o.GovDoc
	}
	return toSerialize, nil
}

type NullableSearchBibs200ResponseBibRecordsInnerClassification struct {
	value *SearchBibs200ResponseBibRecordsInnerClassification
	isSet bool
}

func (v NullableSearchBibs200ResponseBibRecordsInnerClassification) Get() *SearchBibs200ResponseBibRecordsInnerClassification {
	return v.value
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerClassification) Set(val *SearchBibs200ResponseBibRecordsInnerClassification) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBibs200ResponseBibRecordsInnerClassification) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerClassification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBibs200ResponseBibRecordsInnerClassification(val *SearchBibs200ResponseBibRecordsInnerClassification) *NullableSearchBibs200ResponseBibRecordsInnerClassification {
	return &NullableSearchBibs200ResponseBibRecordsInnerClassification{value: val, isSet: true}
}

func (v NullableSearchBibs200ResponseBibRecordsInnerClassification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerClassification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
