/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchBibs200ResponseBibRecordsInnerEditionCluster type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBibs200ResponseBibRecordsInnerEditionCluster{}

// SearchBibs200ResponseBibRecordsInnerEditionCluster struct for SearchBibs200ResponseBibRecordsInnerEditionCluster
type SearchBibs200ResponseBibRecordsInnerEditionCluster struct {
	// An id associated with a particular edition cluster [Admin/Edition/ID]
	Id *string `json:"id,omitempty"`
	// Number of items in edition cluster
	Count *int32 `json:"count,omitempty"`
}

// NewSearchBibs200ResponseBibRecordsInnerEditionCluster instantiates a new SearchBibs200ResponseBibRecordsInnerEditionCluster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBibs200ResponseBibRecordsInnerEditionCluster() *SearchBibs200ResponseBibRecordsInnerEditionCluster {
	this := SearchBibs200ResponseBibRecordsInnerEditionCluster{}
	return &this
}

// NewSearchBibs200ResponseBibRecordsInnerEditionClusterWithDefaults instantiates a new SearchBibs200ResponseBibRecordsInnerEditionCluster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBibs200ResponseBibRecordsInnerEditionClusterWithDefaults() *SearchBibs200ResponseBibRecordsInnerEditionCluster {
	this := SearchBibs200ResponseBibRecordsInnerEditionCluster{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) SetId(v string) {
	o.Id = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SearchBibs200ResponseBibRecordsInnerEditionCluster) SetCount(v int32) {
	o.Count = &v
}

func (o SearchBibs200ResponseBibRecordsInnerEditionCluster) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBibs200ResponseBibRecordsInnerEditionCluster) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	return toSerialize, nil
}

type NullableSearchBibs200ResponseBibRecordsInnerEditionCluster struct {
	value *SearchBibs200ResponseBibRecordsInnerEditionCluster
	isSet bool
}

func (v NullableSearchBibs200ResponseBibRecordsInnerEditionCluster) Get() *SearchBibs200ResponseBibRecordsInnerEditionCluster {
	return v.value
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerEditionCluster) Set(val *SearchBibs200ResponseBibRecordsInnerEditionCluster) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBibs200ResponseBibRecordsInnerEditionCluster) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerEditionCluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBibs200ResponseBibRecordsInnerEditionCluster(val *SearchBibs200ResponseBibRecordsInnerEditionCluster) *NullableSearchBibs200ResponseBibRecordsInnerEditionCluster {
	return &NullableSearchBibs200ResponseBibRecordsInnerEditionCluster{value: val, isSet: true}
}

func (v NullableSearchBibs200ResponseBibRecordsInnerEditionCluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerEditionCluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
