/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner{}

// SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner [v100sa,q,b,c,d,e,4,k v110sa,q,b,c,d,e,4,k,n v111sa,q,c,d,e,j,k,n v700sa,q,b,c,d,e,4,k v710sa,q,b,c,d,e,4,k,n v720sa v711 sa,q,c,d,e,j,k,n v790sa,q,c,d,e,j,k,n v791sa,q,b,c,d,e,4,k v792sa,b,q,c, d,e,j,k,n v796 sa,q,b,c,d,e,4,k v797sa,q,b,c,d,e,4,k,n v798sa,b,q,c, d,e,j,k,n]
type SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner struct {
	FirstName     *SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner `json:"firstName,omitempty"`
	SecondName    *SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner `json:"secondName,omitempty"`
	NonPersonName *SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner `json:"nonPersonName,omitempty"`
	Type          *string                                                   `json:"type,omitempty"`
	// subfield d
	CreatorNotes []string `json:"creatorNotes,omitempty"`
	// subfield e
	Relators []SearchBibs200ResponseBibRecordsInnerTitleAdditionalTitlesInnerRelatorsInner `json:"relators,omitempty"`
	// subfield u
	Affiliation *string `json:"affiliation,omitempty"`
	// whether or not this contributor is the primary one (the 1xx)
	IsPrimary   *bool                                                                    `json:"isPrimary,omitempty"`
	RelatedItem *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerRelatedItem `json:"relatedItem,omitempty"`
}

// NewSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner instantiates a new SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner() *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner {
	this := SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner{}
	return &this
}

// NewSearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerWithDefaults instantiates a new SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerWithDefaults() *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner {
	this := SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetFirstName() SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner {
	if o == nil || IsNil(o.FirstName) {
		var ret SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetFirstNameOk() (*SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner and assigns it to the FirstName field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetFirstName(v SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner) {
	o.FirstName = &v
}

// GetSecondName returns the SecondName field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetSecondName() SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner {
	if o == nil || IsNil(o.SecondName) {
		var ret SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner
		return ret
	}
	return *o.SecondName
}

// GetSecondNameOk returns a tuple with the SecondName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetSecondNameOk() (*SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner, bool) {
	if o == nil || IsNil(o.SecondName) {
		return nil, false
	}
	return o.SecondName, true
}

// HasSecondName returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasSecondName() bool {
	if o != nil && !IsNil(o.SecondName) {
		return true
	}

	return false
}

// SetSecondName gets a reference to the given SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner and assigns it to the SecondName field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetSecondName(v SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner) {
	o.SecondName = &v
}

// GetNonPersonName returns the NonPersonName field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetNonPersonName() SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner {
	if o == nil || IsNil(o.NonPersonName) {
		var ret SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner
		return ret
	}
	return *o.NonPersonName
}

// GetNonPersonNameOk returns a tuple with the NonPersonName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetNonPersonNameOk() (*SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner, bool) {
	if o == nil || IsNil(o.NonPersonName) {
		return nil, false
	}
	return o.NonPersonName, true
}

// HasNonPersonName returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasNonPersonName() bool {
	if o != nil && !IsNil(o.NonPersonName) {
		return true
	}

	return false
}

// SetNonPersonName gets a reference to the given SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner and assigns it to the NonPersonName field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetNonPersonName(v SearchBibs200ResponseBibRecordsInnerTitleMainTitlesInner) {
	o.NonPersonName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetType(v string) {
	o.Type = &v
}

// GetCreatorNotes returns the CreatorNotes field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetCreatorNotes() []string {
	if o == nil || IsNil(o.CreatorNotes) {
		var ret []string
		return ret
	}
	return o.CreatorNotes
}

// GetCreatorNotesOk returns a tuple with the CreatorNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetCreatorNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.CreatorNotes) {
		return nil, false
	}
	return o.CreatorNotes, true
}

// HasCreatorNotes returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasCreatorNotes() bool {
	if o != nil && !IsNil(o.CreatorNotes) {
		return true
	}

	return false
}

// SetCreatorNotes gets a reference to the given []string and assigns it to the CreatorNotes field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetCreatorNotes(v []string) {
	o.CreatorNotes = v
}

// GetRelators returns the Relators field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetRelators() []SearchBibs200ResponseBibRecordsInnerTitleAdditionalTitlesInnerRelatorsInner {
	if o == nil || IsNil(o.Relators) {
		var ret []SearchBibs200ResponseBibRecordsInnerTitleAdditionalTitlesInnerRelatorsInner
		return ret
	}
	return o.Relators
}

// GetRelatorsOk returns a tuple with the Relators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetRelatorsOk() ([]SearchBibs200ResponseBibRecordsInnerTitleAdditionalTitlesInnerRelatorsInner, bool) {
	if o == nil || IsNil(o.Relators) {
		return nil, false
	}
	return o.Relators, true
}

// HasRelators returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasRelators() bool {
	if o != nil && !IsNil(o.Relators) {
		return true
	}

	return false
}

// SetRelators gets a reference to the given []SearchBibs200ResponseBibRecordsInnerTitleAdditionalTitlesInnerRelatorsInner and assigns it to the Relators field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetRelators(v []SearchBibs200ResponseBibRecordsInnerTitleAdditionalTitlesInnerRelatorsInner) {
	o.Relators = v
}

// GetAffiliation returns the Affiliation field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetAffiliation() string {
	if o == nil || IsNil(o.Affiliation) {
		var ret string
		return ret
	}
	return *o.Affiliation
}

// GetAffiliationOk returns a tuple with the Affiliation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetAffiliationOk() (*string, bool) {
	if o == nil || IsNil(o.Affiliation) {
		return nil, false
	}
	return o.Affiliation, true
}

// HasAffiliation returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasAffiliation() bool {
	if o != nil && !IsNil(o.Affiliation) {
		return true
	}

	return false
}

// SetAffiliation gets a reference to the given string and assigns it to the Affiliation field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetAffiliation(v string) {
	o.Affiliation = &v
}

// GetIsPrimary returns the IsPrimary field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetIsPrimary() bool {
	if o == nil || IsNil(o.IsPrimary) {
		var ret bool
		return ret
	}
	return *o.IsPrimary
}

// GetIsPrimaryOk returns a tuple with the IsPrimary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetIsPrimaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrimary) {
		return nil, false
	}
	return o.IsPrimary, true
}

// HasIsPrimary returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasIsPrimary() bool {
	if o != nil && !IsNil(o.IsPrimary) {
		return true
	}

	return false
}

// SetIsPrimary gets a reference to the given bool and assigns it to the IsPrimary field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetIsPrimary(v bool) {
	o.IsPrimary = &v
}

// GetRelatedItem returns the RelatedItem field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetRelatedItem() SearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerRelatedItem {
	if o == nil || IsNil(o.RelatedItem) {
		var ret SearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerRelatedItem
		return ret
	}
	return *o.RelatedItem
}

// GetRelatedItemOk returns a tuple with the RelatedItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) GetRelatedItemOk() (*SearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerRelatedItem, bool) {
	if o == nil || IsNil(o.RelatedItem) {
		return nil, false
	}
	return o.RelatedItem, true
}

// HasRelatedItem returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) HasRelatedItem() bool {
	if o != nil && !IsNil(o.RelatedItem) {
		return true
	}

	return false
}

// SetRelatedItem gets a reference to the given SearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerRelatedItem and assigns it to the RelatedItem field.
func (o *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) SetRelatedItem(v SearchBibs200ResponseBibRecordsInnerContributorCreatorsInnerRelatedItem) {
	o.RelatedItem = &v
}

func (o SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["firstName"] = o.FirstName
	}
	if !IsNil(o.SecondName) {
		toSerialize["secondName"] = o.SecondName
	}
	if !IsNil(o.NonPersonName) {
		toSerialize["nonPersonName"] = o.NonPersonName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.CreatorNotes) {
		toSerialize["creatorNotes"] = o.CreatorNotes
	}
	if !IsNil(o.Relators) {
		toSerialize["relators"] = o.Relators
	}
	if !IsNil(o.Affiliation) {
		toSerialize["affiliation"] = o.Affiliation
	}
	if !IsNil(o.IsPrimary) {
		toSerialize["isPrimary"] = o.IsPrimary
	}
	if !IsNil(o.RelatedItem) {
		toSerialize["relatedItem"] = o.RelatedItem
	}
	return toSerialize, nil
}

type NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner struct {
	value *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner
	isSet bool
}

func (v NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) Get() *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner {
	return v.value
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) Set(val *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner(val *SearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) *NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner {
	return &NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner{value: val, isSet: true}
}

func (v NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerContributorCreatorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
