/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner{}

// FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner struct for FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner
type FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner struct {
	// Field link and sequence number [852/863-865/866-868/876-878 | s8]
	LinkingAndSequenceNumber *string `json:"linkingAndSequenceNumber,omitempty"`
	// Summary of Holdings [https://www.loc.gov/marc/holdings/echdcntf.html]
	SummaryOfHoldings *string `json:"summaryOfHoldings,omitempty"`
	// Enumerations [853-855/863-865 |a-h]
	Enumerations []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner `json:"enumerations,omitempty"`
	// Chronologies [853-855/863-865 |i-v]
	Chronologies []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner `json:"chronologies,omitempty"`
	// [866-8 |a]
	TextualHoldings *string `json:"textualHoldings,omitempty"`
	// [876-8 |3]
	ItemMaterialSpecified *string `json:"itemMaterialSpecified,omitempty"`
	// Piece Designation [852/863-865/866-868/876-878 |p]
	PieceDesignation *string `json:"pieceDesignation,omitempty"`
	// Cancelled Piece Designation [876-878 |r]
	CancelledPieceDesignations []string `json:"cancelledPieceDesignations,omitempty"`
	// Temporary location [876-878 |l]
	TemporaryLocation *string `json:"temporaryLocation,omitempty"`
	// Public notes [852/863-865/866-868/876-878 |z]
	PublicNotes []string `json:"publicNotes,omitempty"`
	// Year as Range [si]
	YearRanges []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner `json:"yearRanges,omitempty"`
	// Volume Number As Range [sb]
	VolumeRanges []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner `json:"volumeRanges,omitempty"`
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner{}
	return &this
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerWithDefaults instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerWithDefaults() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner{}
	return &this
}

// GetLinkingAndSequenceNumber returns the LinkingAndSequenceNumber field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetLinkingAndSequenceNumber() string {
	if o == nil || IsNil(o.LinkingAndSequenceNumber) {
		var ret string
		return ret
	}
	return *o.LinkingAndSequenceNumber
}

// GetLinkingAndSequenceNumberOk returns a tuple with the LinkingAndSequenceNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetLinkingAndSequenceNumberOk() (*string, bool) {
	if o == nil || IsNil(o.LinkingAndSequenceNumber) {
		return nil, false
	}
	return o.LinkingAndSequenceNumber, true
}

// HasLinkingAndSequenceNumber returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasLinkingAndSequenceNumber() bool {
	if o != nil && !IsNil(o.LinkingAndSequenceNumber) {
		return true
	}

	return false
}

// SetLinkingAndSequenceNumber gets a reference to the given string and assigns it to the LinkingAndSequenceNumber field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetLinkingAndSequenceNumber(v string) {
	o.LinkingAndSequenceNumber = &v
}

// GetSummaryOfHoldings returns the SummaryOfHoldings field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetSummaryOfHoldings() string {
	if o == nil || IsNil(o.SummaryOfHoldings) {
		var ret string
		return ret
	}
	return *o.SummaryOfHoldings
}

// GetSummaryOfHoldingsOk returns a tuple with the SummaryOfHoldings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetSummaryOfHoldingsOk() (*string, bool) {
	if o == nil || IsNil(o.SummaryOfHoldings) {
		return nil, false
	}
	return o.SummaryOfHoldings, true
}

// HasSummaryOfHoldings returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasSummaryOfHoldings() bool {
	if o != nil && !IsNil(o.SummaryOfHoldings) {
		return true
	}

	return false
}

// SetSummaryOfHoldings gets a reference to the given string and assigns it to the SummaryOfHoldings field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetSummaryOfHoldings(v string) {
	o.SummaryOfHoldings = &v
}

// GetEnumerations returns the Enumerations field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetEnumerations() []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner {
	if o == nil || IsNil(o.Enumerations) {
		var ret []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner
		return ret
	}
	return o.Enumerations
}

// GetEnumerationsOk returns a tuple with the Enumerations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetEnumerationsOk() ([]FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner, bool) {
	if o == nil || IsNil(o.Enumerations) {
		return nil, false
	}
	return o.Enumerations, true
}

// HasEnumerations returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasEnumerations() bool {
	if o != nil && !IsNil(o.Enumerations) {
		return true
	}

	return false
}

// SetEnumerations gets a reference to the given []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner and assigns it to the Enumerations field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetEnumerations(v []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner) {
	o.Enumerations = v
}

// GetChronologies returns the Chronologies field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetChronologies() []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner {
	if o == nil || IsNil(o.Chronologies) {
		var ret []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner
		return ret
	}
	return o.Chronologies
}

// GetChronologiesOk returns a tuple with the Chronologies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetChronologiesOk() ([]FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner, bool) {
	if o == nil || IsNil(o.Chronologies) {
		return nil, false
	}
	return o.Chronologies, true
}

// HasChronologies returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasChronologies() bool {
	if o != nil && !IsNil(o.Chronologies) {
		return true
	}

	return false
}

// SetChronologies gets a reference to the given []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner and assigns it to the Chronologies field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetChronologies(v []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerEnumerationsInner) {
	o.Chronologies = v
}

// GetTextualHoldings returns the TextualHoldings field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetTextualHoldings() string {
	if o == nil || IsNil(o.TextualHoldings) {
		var ret string
		return ret
	}
	return *o.TextualHoldings
}

// GetTextualHoldingsOk returns a tuple with the TextualHoldings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetTextualHoldingsOk() (*string, bool) {
	if o == nil || IsNil(o.TextualHoldings) {
		return nil, false
	}
	return o.TextualHoldings, true
}

// HasTextualHoldings returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasTextualHoldings() bool {
	if o != nil && !IsNil(o.TextualHoldings) {
		return true
	}

	return false
}

// SetTextualHoldings gets a reference to the given string and assigns it to the TextualHoldings field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetTextualHoldings(v string) {
	o.TextualHoldings = &v
}

// GetItemMaterialSpecified returns the ItemMaterialSpecified field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetItemMaterialSpecified() string {
	if o == nil || IsNil(o.ItemMaterialSpecified) {
		var ret string
		return ret
	}
	return *o.ItemMaterialSpecified
}

// GetItemMaterialSpecifiedOk returns a tuple with the ItemMaterialSpecified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetItemMaterialSpecifiedOk() (*string, bool) {
	if o == nil || IsNil(o.ItemMaterialSpecified) {
		return nil, false
	}
	return o.ItemMaterialSpecified, true
}

// HasItemMaterialSpecified returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasItemMaterialSpecified() bool {
	if o != nil && !IsNil(o.ItemMaterialSpecified) {
		return true
	}

	return false
}

// SetItemMaterialSpecified gets a reference to the given string and assigns it to the ItemMaterialSpecified field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetItemMaterialSpecified(v string) {
	o.ItemMaterialSpecified = &v
}

// GetPieceDesignation returns the PieceDesignation field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetPieceDesignation() string {
	if o == nil || IsNil(o.PieceDesignation) {
		var ret string
		return ret
	}
	return *o.PieceDesignation
}

// GetPieceDesignationOk returns a tuple with the PieceDesignation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetPieceDesignationOk() (*string, bool) {
	if o == nil || IsNil(o.PieceDesignation) {
		return nil, false
	}
	return o.PieceDesignation, true
}

// HasPieceDesignation returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasPieceDesignation() bool {
	if o != nil && !IsNil(o.PieceDesignation) {
		return true
	}

	return false
}

// SetPieceDesignation gets a reference to the given string and assigns it to the PieceDesignation field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetPieceDesignation(v string) {
	o.PieceDesignation = &v
}

// GetCancelledPieceDesignations returns the CancelledPieceDesignations field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetCancelledPieceDesignations() []string {
	if o == nil || IsNil(o.CancelledPieceDesignations) {
		var ret []string
		return ret
	}
	return o.CancelledPieceDesignations
}

// GetCancelledPieceDesignationsOk returns a tuple with the CancelledPieceDesignations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetCancelledPieceDesignationsOk() ([]string, bool) {
	if o == nil || IsNil(o.CancelledPieceDesignations) {
		return nil, false
	}
	return o.CancelledPieceDesignations, true
}

// HasCancelledPieceDesignations returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasCancelledPieceDesignations() bool {
	if o != nil && !IsNil(o.CancelledPieceDesignations) {
		return true
	}

	return false
}

// SetCancelledPieceDesignations gets a reference to the given []string and assigns it to the CancelledPieceDesignations field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetCancelledPieceDesignations(v []string) {
	o.CancelledPieceDesignations = v
}

// GetTemporaryLocation returns the TemporaryLocation field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetTemporaryLocation() string {
	if o == nil || IsNil(o.TemporaryLocation) {
		var ret string
		return ret
	}
	return *o.TemporaryLocation
}

// GetTemporaryLocationOk returns a tuple with the TemporaryLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetTemporaryLocationOk() (*string, bool) {
	if o == nil || IsNil(o.TemporaryLocation) {
		return nil, false
	}
	return o.TemporaryLocation, true
}

// HasTemporaryLocation returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasTemporaryLocation() bool {
	if o != nil && !IsNil(o.TemporaryLocation) {
		return true
	}

	return false
}

// SetTemporaryLocation gets a reference to the given string and assigns it to the TemporaryLocation field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetTemporaryLocation(v string) {
	o.TemporaryLocation = &v
}

// GetPublicNotes returns the PublicNotes field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetPublicNotes() []string {
	if o == nil || IsNil(o.PublicNotes) {
		var ret []string
		return ret
	}
	return o.PublicNotes
}

// GetPublicNotesOk returns a tuple with the PublicNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetPublicNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.PublicNotes) {
		return nil, false
	}
	return o.PublicNotes, true
}

// HasPublicNotes returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasPublicNotes() bool {
	if o != nil && !IsNil(o.PublicNotes) {
		return true
	}

	return false
}

// SetPublicNotes gets a reference to the given []string and assigns it to the PublicNotes field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetPublicNotes(v []string) {
	o.PublicNotes = v
}

// GetYearRanges returns the YearRanges field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetYearRanges() []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner {
	if o == nil || IsNil(o.YearRanges) {
		var ret []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner
		return ret
	}
	return o.YearRanges
}

// GetYearRangesOk returns a tuple with the YearRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetYearRangesOk() ([]FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner, bool) {
	if o == nil || IsNil(o.YearRanges) {
		return nil, false
	}
	return o.YearRanges, true
}

// HasYearRanges returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasYearRanges() bool {
	if o != nil && !IsNil(o.YearRanges) {
		return true
	}

	return false
}

// SetYearRanges gets a reference to the given []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner and assigns it to the YearRanges field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetYearRanges(v []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) {
	o.YearRanges = v
}

// GetVolumeRanges returns the VolumeRanges field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetVolumeRanges() []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner {
	if o == nil || IsNil(o.VolumeRanges) {
		var ret []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner
		return ret
	}
	return o.VolumeRanges
}

// GetVolumeRangesOk returns a tuple with the VolumeRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) GetVolumeRangesOk() ([]FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner, bool) {
	if o == nil || IsNil(o.VolumeRanges) {
		return nil, false
	}
	return o.VolumeRanges, true
}

// HasVolumeRanges returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) HasVolumeRanges() bool {
	if o != nil && !IsNil(o.VolumeRanges) {
		return true
	}

	return false
}

// SetVolumeRanges gets a reference to the given []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner and assigns it to the VolumeRanges field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) SetVolumeRanges(v []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) {
	o.VolumeRanges = v
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LinkingAndSequenceNumber) {
		toSerialize["linkingAndSequenceNumber"] = o.LinkingAndSequenceNumber
	}
	if !IsNil(o.SummaryOfHoldings) {
		toSerialize["summaryOfHoldings"] = o.SummaryOfHoldings
	}
	if !IsNil(o.Enumerations) {
		toSerialize["enumerations"] = o.Enumerations
	}
	if !IsNil(o.Chronologies) {
		toSerialize["chronologies"] = o.Chronologies
	}
	if !IsNil(o.TextualHoldings) {
		toSerialize["textualHoldings"] = o.TextualHoldings
	}
	if !IsNil(o.ItemMaterialSpecified) {
		toSerialize["itemMaterialSpecified"] = o.ItemMaterialSpecified
	}
	if !IsNil(o.PieceDesignation) {
		toSerialize["pieceDesignation"] = o.PieceDesignation
	}
	if !IsNil(o.CancelledPieceDesignations) {
		toSerialize["cancelledPieceDesignations"] = o.CancelledPieceDesignations
	}
	if !IsNil(o.TemporaryLocation) {
		toSerialize["temporaryLocation"] = o.TemporaryLocation
	}
	if !IsNil(o.PublicNotes) {
		toSerialize["publicNotes"] = o.PublicNotes
	}
	if !IsNil(o.YearRanges) {
		toSerialize["yearRanges"] = o.YearRanges
	}
	if !IsNil(o.VolumeRanges) {
		toSerialize["volumeRanges"] = o.VolumeRanges
	}
	return toSerialize, nil
}

type NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner struct {
	value *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner
	isSet bool
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) Get() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner {
	return v.value
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) Set(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner {
	return &NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner{value: val, isSet: true}
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
