/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1{}

// FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 struct for FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1
type FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 struct {
	// LHR Control Number [LHR -> HldDetRec/c001]
	LhrControlNumber string `json:"lhrControlNumber"`
	// LHR Date Entered [LHR -> HldDetRec/Admin/CreateDate]
	LhrDateEntered string `json:"lhrDateEntered"`
	// LHR Date Last Used [LHR -> HldDetRec/Admin/ReplacedDate]
	LhrLastUpdated string `json:"lhrLastUpdated"`
	// OCLC Number [LHR -> HldDetRec/c004]
	OclcNumber string `json:"oclcNumber"`
	// material format [LHR -> HldDetRec/c007]
	Format   string                                                                                    `json:"format"`
	Location *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1Location `json:"location,omitempty"`
	// copy number [LHR -> HldDetRec/v852st]
	CopyNumber *string                                                                                     `json:"copyNumber,omitempty"`
	CallNumber *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber `json:"callNumber,omitempty"`
	// local lending policy [LHR -> HldDetRec/Admin/Lend]
	LendingPolicy string `json:"lendingPolicy"`
	// institution has shared print commitment [Holdings/LibHasSharedPrint || LHR -> HldDetRec/Admin/SPReg]
	HasSharedPrintCommitment string `json:"hasSharedPrintCommitment"`
	// shared print details [LHR -> HldDetRec/v583]
	SharedPrintCommitments []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1SharedPrintCommitmentsInner `json:"sharedPrintCommitments,omitempty"`
	// summary statement [LHR -> HldSummRec/v966sa]
	Summary *string `json:"summary,omitempty"`
	// Textual Holding [LHR -> HldDetRec/v866,v867,v868] Item Information Holding [LHR -> HldDetRec/v876,v877,v878] Enumeration Chronology Holding [LHR -> HldDetRec/v863,v864,v865]
	HoldingParts []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner `json:"holdingParts,omitempty"`
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1(lhrControlNumber string, lhrDateEntered string, lhrLastUpdated string, oclcNumber string, format string, lendingPolicy string, hasSharedPrintCommitment string) *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1{}
	this.LhrControlNumber = lhrControlNumber
	this.LhrDateEntered = lhrDateEntered
	this.LhrLastUpdated = lhrLastUpdated
	this.OclcNumber = oclcNumber
	this.Format = format
	this.LendingPolicy = lendingPolicy
	this.HasSharedPrintCommitment = hasSharedPrintCommitment
	return &this
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1WithDefaults instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1WithDefaults() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1{}
	return &this
}

// GetLhrControlNumber returns the LhrControlNumber field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLhrControlNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LhrControlNumber
}

// GetLhrControlNumberOk returns a tuple with the LhrControlNumber field value
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLhrControlNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LhrControlNumber, true
}

// SetLhrControlNumber sets field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetLhrControlNumber(v string) {
	o.LhrControlNumber = v
}

// GetLhrDateEntered returns the LhrDateEntered field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLhrDateEntered() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LhrDateEntered
}

// GetLhrDateEnteredOk returns a tuple with the LhrDateEntered field value
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLhrDateEnteredOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LhrDateEntered, true
}

// SetLhrDateEntered sets field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetLhrDateEntered(v string) {
	o.LhrDateEntered = v
}

// GetLhrLastUpdated returns the LhrLastUpdated field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLhrLastUpdated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LhrLastUpdated
}

// GetLhrLastUpdatedOk returns a tuple with the LhrLastUpdated field value
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLhrLastUpdatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LhrLastUpdated, true
}

// SetLhrLastUpdated sets field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetLhrLastUpdated(v string) {
	o.LhrLastUpdated = v
}

// GetOclcNumber returns the OclcNumber field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetOclcNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OclcNumber
}

// GetOclcNumberOk returns a tuple with the OclcNumber field value
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetOclcNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OclcNumber, true
}

// SetOclcNumber sets field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetOclcNumber(v string) {
	o.OclcNumber = v
}

// GetFormat returns the Format field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetFormat(v string) {
	o.Format = v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLocation() FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1Location {
	if o == nil || IsNil(o.Location) {
		var ret FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1Location
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLocationOk() (*FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1Location, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1Location and assigns it to the Location field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetLocation(v FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1Location) {
	o.Location = &v
}

// GetCopyNumber returns the CopyNumber field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetCopyNumber() string {
	if o == nil || IsNil(o.CopyNumber) {
		var ret string
		return ret
	}
	return *o.CopyNumber
}

// GetCopyNumberOk returns a tuple with the CopyNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetCopyNumberOk() (*string, bool) {
	if o == nil || IsNil(o.CopyNumber) {
		return nil, false
	}
	return o.CopyNumber, true
}

// HasCopyNumber returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) HasCopyNumber() bool {
	if o != nil && !IsNil(o.CopyNumber) {
		return true
	}

	return false
}

// SetCopyNumber gets a reference to the given string and assigns it to the CopyNumber field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetCopyNumber(v string) {
	o.CopyNumber = &v
}

// GetCallNumber returns the CallNumber field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetCallNumber() FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber {
	if o == nil || IsNil(o.CallNumber) {
		var ret FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber
		return ret
	}
	return *o.CallNumber
}

// GetCallNumberOk returns a tuple with the CallNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetCallNumberOk() (*FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber, bool) {
	if o == nil || IsNil(o.CallNumber) {
		return nil, false
	}
	return o.CallNumber, true
}

// HasCallNumber returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) HasCallNumber() bool {
	if o != nil && !IsNil(o.CallNumber) {
		return true
	}

	return false
}

// SetCallNumber gets a reference to the given FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber and assigns it to the CallNumber field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetCallNumber(v FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) {
	o.CallNumber = &v
}

// GetLendingPolicy returns the LendingPolicy field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLendingPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LendingPolicy
}

// GetLendingPolicyOk returns a tuple with the LendingPolicy field value
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetLendingPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LendingPolicy, true
}

// SetLendingPolicy sets field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetLendingPolicy(v string) {
	o.LendingPolicy = v
}

// GetHasSharedPrintCommitment returns the HasSharedPrintCommitment field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetHasSharedPrintCommitment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HasSharedPrintCommitment
}

// GetHasSharedPrintCommitmentOk returns a tuple with the HasSharedPrintCommitment field value
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetHasSharedPrintCommitmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasSharedPrintCommitment, true
}

// SetHasSharedPrintCommitment sets field value
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetHasSharedPrintCommitment(v string) {
	o.HasSharedPrintCommitment = v
}

// GetSharedPrintCommitments returns the SharedPrintCommitments field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetSharedPrintCommitments() []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1SharedPrintCommitmentsInner {
	if o == nil || IsNil(o.SharedPrintCommitments) {
		var ret []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1SharedPrintCommitmentsInner
		return ret
	}
	return o.SharedPrintCommitments
}

// GetSharedPrintCommitmentsOk returns a tuple with the SharedPrintCommitments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetSharedPrintCommitmentsOk() ([]FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1SharedPrintCommitmentsInner, bool) {
	if o == nil || IsNil(o.SharedPrintCommitments) {
		return nil, false
	}
	return o.SharedPrintCommitments, true
}

// HasSharedPrintCommitments returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) HasSharedPrintCommitments() bool {
	if o != nil && !IsNil(o.SharedPrintCommitments) {
		return true
	}

	return false
}

// SetSharedPrintCommitments gets a reference to the given []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1SharedPrintCommitmentsInner and assigns it to the SharedPrintCommitments field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetSharedPrintCommitments(v []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1SharedPrintCommitmentsInner) {
	o.SharedPrintCommitments = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetSummary(v string) {
	o.Summary = &v
}

// GetHoldingParts returns the HoldingParts field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetHoldingParts() []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner {
	if o == nil || IsNil(o.HoldingParts) {
		var ret []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner
		return ret
	}
	return o.HoldingParts
}

// GetHoldingPartsOk returns a tuple with the HoldingParts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) GetHoldingPartsOk() ([]FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner, bool) {
	if o == nil || IsNil(o.HoldingParts) {
		return nil, false
	}
	return o.HoldingParts, true
}

// HasHoldingParts returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) HasHoldingParts() bool {
	if o != nil && !IsNil(o.HoldingParts) {
		return true
	}

	return false
}

// SetHoldingParts gets a reference to the given []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner and assigns it to the HoldingParts field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) SetHoldingParts(v []FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInner) {
	o.HoldingParts = v
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["lhrControlNumber"] = o.LhrControlNumber
	toSerialize["lhrDateEntered"] = o.LhrDateEntered
	toSerialize["lhrLastUpdated"] = o.LhrLastUpdated
	toSerialize["oclcNumber"] = o.OclcNumber
	toSerialize["format"] = o.Format
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.CopyNumber) {
		toSerialize["copyNumber"] = o.CopyNumber
	}
	if !IsNil(o.CallNumber) {
		toSerialize["callNumber"] = o.CallNumber
	}
	toSerialize["lendingPolicy"] = o.LendingPolicy
	toSerialize["hasSharedPrintCommitment"] = o.HasSharedPrintCommitment
	if !IsNil(o.SharedPrintCommitments) {
		toSerialize["sharedPrintCommitments"] = o.SharedPrintCommitments
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.HoldingParts) {
		toSerialize["holdingParts"] = o.HoldingParts
	}
	return toSerialize, nil
}

type NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 struct {
	value *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1
	isSet bool
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) Get() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 {
	return v.value
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) Set(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) {
	v.value = val
	v.isSet = true
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) IsSet() bool {
	return v.isSet
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1 {
	return &NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1{value: val, isSet: true}
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
