/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner{}

// FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner struct for FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner
type FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner struct {
	// Country of holding institution [Holdings/Library/Country]
	Country *string `json:"country,omitempty"`
	// State of holding institution [Holdings/Library/State]
	State *string `json:"state,omitempty"`
	// Oclc Symbol of holding institution [Holdings/Library/InstSym]
	OclcSymbol *string `json:"oclcSymbol,omitempty"`
	// The identifier in the WorldCat Registry for the institution
	RegistryId *int32 `json:"registryId,omitempty"`
	// Name of holding institution [Holdings/Library/InstName]
	InstitutionName *string `json:"institutionName,omitempty"`
	// Some name the library might also be called
	AlsoCalled *string                                                                                 `json:"alsoCalled,omitempty"`
	Address    *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerAddress `json:"address,omitempty"`
	// The type of institution
	InstitutionType *string `json:"institutionType,omitempty"`
	// Whether or not the library has an OPAC deep links
	HasOPACLink *bool `json:"hasOPACLink,omitempty"`
	// Distance from location if lat/log was specified
	Distance *string `json:"distance,omitempty"`
	// URI to find more info about the institution
	Self *string `json:"self,omitempty"`
	// ILL status [Holdings/Library/ILLStatus]
	IllStatus *string `json:"illStatus,omitempty"`
	// ILL group [Holdings/Library/ILLGroup]
	IllGroup *string `json:"illGroup,omitempty"`
	// institution has shared print commitment [Holdings/LibHasSharedPrint]
	HasSharedPrintCommitment *string `json:"hasSharedPrintCommitment,omitempty"`
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner{}
	return &this
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerWithDefaults instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerWithDefaults() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner{}
	return &this
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetCountry(v string) {
	o.Country = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetState(v string) {
	o.State = &v
}

// GetOclcSymbol returns the OclcSymbol field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetOclcSymbol() string {
	if o == nil || IsNil(o.OclcSymbol) {
		var ret string
		return ret
	}
	return *o.OclcSymbol
}

// GetOclcSymbolOk returns a tuple with the OclcSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetOclcSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.OclcSymbol) {
		return nil, false
	}
	return o.OclcSymbol, true
}

// HasOclcSymbol returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasOclcSymbol() bool {
	if o != nil && !IsNil(o.OclcSymbol) {
		return true
	}

	return false
}

// SetOclcSymbol gets a reference to the given string and assigns it to the OclcSymbol field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetOclcSymbol(v string) {
	o.OclcSymbol = &v
}

// GetRegistryId returns the RegistryId field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetRegistryId() int32 {
	if o == nil || IsNil(o.RegistryId) {
		var ret int32
		return ret
	}
	return *o.RegistryId
}

// GetRegistryIdOk returns a tuple with the RegistryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetRegistryIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RegistryId) {
		return nil, false
	}
	return o.RegistryId, true
}

// HasRegistryId returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasRegistryId() bool {
	if o != nil && !IsNil(o.RegistryId) {
		return true
	}

	return false
}

// SetRegistryId gets a reference to the given int32 and assigns it to the RegistryId field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetRegistryId(v int32) {
	o.RegistryId = &v
}

// GetInstitutionName returns the InstitutionName field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetInstitutionName() string {
	if o == nil || IsNil(o.InstitutionName) {
		var ret string
		return ret
	}
	return *o.InstitutionName
}

// GetInstitutionNameOk returns a tuple with the InstitutionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetInstitutionNameOk() (*string, bool) {
	if o == nil || IsNil(o.InstitutionName) {
		return nil, false
	}
	return o.InstitutionName, true
}

// HasInstitutionName returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasInstitutionName() bool {
	if o != nil && !IsNil(o.InstitutionName) {
		return true
	}

	return false
}

// SetInstitutionName gets a reference to the given string and assigns it to the InstitutionName field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetInstitutionName(v string) {
	o.InstitutionName = &v
}

// GetAlsoCalled returns the AlsoCalled field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetAlsoCalled() string {
	if o == nil || IsNil(o.AlsoCalled) {
		var ret string
		return ret
	}
	return *o.AlsoCalled
}

// GetAlsoCalledOk returns a tuple with the AlsoCalled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetAlsoCalledOk() (*string, bool) {
	if o == nil || IsNil(o.AlsoCalled) {
		return nil, false
	}
	return o.AlsoCalled, true
}

// HasAlsoCalled returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasAlsoCalled() bool {
	if o != nil && !IsNil(o.AlsoCalled) {
		return true
	}

	return false
}

// SetAlsoCalled gets a reference to the given string and assigns it to the AlsoCalled field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetAlsoCalled(v string) {
	o.AlsoCalled = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetAddress() FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerAddress {
	if o == nil || IsNil(o.Address) {
		var ret FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetAddressOk() (*FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerAddress and assigns it to the Address field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetAddress(v FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInnerAddress) {
	o.Address = &v
}

// GetInstitutionType returns the InstitutionType field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetInstitutionType() string {
	if o == nil || IsNil(o.InstitutionType) {
		var ret string
		return ret
	}
	return *o.InstitutionType
}

// GetInstitutionTypeOk returns a tuple with the InstitutionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetInstitutionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstitutionType) {
		return nil, false
	}
	return o.InstitutionType, true
}

// HasInstitutionType returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasInstitutionType() bool {
	if o != nil && !IsNil(o.InstitutionType) {
		return true
	}

	return false
}

// SetInstitutionType gets a reference to the given string and assigns it to the InstitutionType field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetInstitutionType(v string) {
	o.InstitutionType = &v
}

// GetHasOPACLink returns the HasOPACLink field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetHasOPACLink() bool {
	if o == nil || IsNil(o.HasOPACLink) {
		var ret bool
		return ret
	}
	return *o.HasOPACLink
}

// GetHasOPACLinkOk returns a tuple with the HasOPACLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetHasOPACLinkOk() (*bool, bool) {
	if o == nil || IsNil(o.HasOPACLink) {
		return nil, false
	}
	return o.HasOPACLink, true
}

// HasHasOPACLink returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasHasOPACLink() bool {
	if o != nil && !IsNil(o.HasOPACLink) {
		return true
	}

	return false
}

// SetHasOPACLink gets a reference to the given bool and assigns it to the HasOPACLink field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetHasOPACLink(v bool) {
	o.HasOPACLink = &v
}

// GetDistance returns the Distance field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetDistance() string {
	if o == nil || IsNil(o.Distance) {
		var ret string
		return ret
	}
	return *o.Distance
}

// GetDistanceOk returns a tuple with the Distance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetDistanceOk() (*string, bool) {
	if o == nil || IsNil(o.Distance) {
		return nil, false
	}
	return o.Distance, true
}

// HasDistance returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasDistance() bool {
	if o != nil && !IsNil(o.Distance) {
		return true
	}

	return false
}

// SetDistance gets a reference to the given string and assigns it to the Distance field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetDistance(v string) {
	o.Distance = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetSelf(v string) {
	o.Self = &v
}

// GetIllStatus returns the IllStatus field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetIllStatus() string {
	if o == nil || IsNil(o.IllStatus) {
		var ret string
		return ret
	}
	return *o.IllStatus
}

// GetIllStatusOk returns a tuple with the IllStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetIllStatusOk() (*string, bool) {
	if o == nil || IsNil(o.IllStatus) {
		return nil, false
	}
	return o.IllStatus, true
}

// HasIllStatus returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasIllStatus() bool {
	if o != nil && !IsNil(o.IllStatus) {
		return true
	}

	return false
}

// SetIllStatus gets a reference to the given string and assigns it to the IllStatus field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetIllStatus(v string) {
	o.IllStatus = &v
}

// GetIllGroup returns the IllGroup field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetIllGroup() string {
	if o == nil || IsNil(o.IllGroup) {
		var ret string
		return ret
	}
	return *o.IllGroup
}

// GetIllGroupOk returns a tuple with the IllGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetIllGroupOk() (*string, bool) {
	if o == nil || IsNil(o.IllGroup) {
		return nil, false
	}
	return o.IllGroup, true
}

// HasIllGroup returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasIllGroup() bool {
	if o != nil && !IsNil(o.IllGroup) {
		return true
	}

	return false
}

// SetIllGroup gets a reference to the given string and assigns it to the IllGroup field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetIllGroup(v string) {
	o.IllGroup = &v
}

// GetHasSharedPrintCommitment returns the HasSharedPrintCommitment field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetHasSharedPrintCommitment() string {
	if o == nil || IsNil(o.HasSharedPrintCommitment) {
		var ret string
		return ret
	}
	return *o.HasSharedPrintCommitment
}

// GetHasSharedPrintCommitmentOk returns a tuple with the HasSharedPrintCommitment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) GetHasSharedPrintCommitmentOk() (*string, bool) {
	if o == nil || IsNil(o.HasSharedPrintCommitment) {
		return nil, false
	}
	return o.HasSharedPrintCommitment, true
}

// HasHasSharedPrintCommitment returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) HasHasSharedPrintCommitment() bool {
	if o != nil && !IsNil(o.HasSharedPrintCommitment) {
		return true
	}

	return false
}

// SetHasSharedPrintCommitment gets a reference to the given string and assigns it to the HasSharedPrintCommitment field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) SetHasSharedPrintCommitment(v string) {
	o.HasSharedPrintCommitment = &v
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.OclcSymbol) {
		toSerialize["oclcSymbol"] = o.OclcSymbol
	}
	if !IsNil(o.RegistryId) {
		toSerialize["registryId"] = o.RegistryId
	}
	if !IsNil(o.InstitutionName) {
		toSerialize["institutionName"] = o.InstitutionName
	}
	if !IsNil(o.AlsoCalled) {
		toSerialize["alsoCalled"] = o.AlsoCalled
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.InstitutionType) {
		toSerialize["institutionType"] = o.InstitutionType
	}
	if !IsNil(o.HasOPACLink) {
		toSerialize["hasOPACLink"] = o.HasOPACLink
	}
	if !IsNil(o.Distance) {
		toSerialize["distance"] = o.Distance
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.IllStatus) {
		toSerialize["illStatus"] = o.IllStatus
	}
	if !IsNil(o.IllGroup) {
		toSerialize["illGroup"] = o.IllGroup
	}
	if !IsNil(o.HasSharedPrintCommitment) {
		toSerialize["hasSharedPrintCommitment"] = o.HasSharedPrintCommitment
	}
	return toSerialize, nil
}

type NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner struct {
	value *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner
	isSet bool
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) Get() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner {
	return v.value
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) Set(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner {
	return &NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner{value: val, isSet: true}
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
