/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchBibs200ResponseBibRecordsInnerIdentifier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBibs200ResponseBibRecordsInnerIdentifier{}

// SearchBibs200ResponseBibRecordsInnerIdentifier struct for SearchBibs200ResponseBibRecordsInnerIdentifier
type SearchBibs200ResponseBibRecordsInnerIdentifier struct {
	// OCLC Number [Admin/BaseOCLCNo || Admin/OCLCNo || C001]
	OclcNumber *int64 `json:"oclcNumber,omitempty"`
	// Library of Congress Control Number [v010sa]
	Lccn *string `json:"lccn,omitempty"`
	// International Standard Book Number [v020sa]
	Isbns []string `json:"isbns,omitempty"`
	// International Standard Serial Numbers
	Issns []string `json:"issns,omitempty"`
	// External System Control Number [v029sa,b,c,t]
	ExternalIdentifiers []SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner `json:"externalIdentifiers,omitempty"`
	// Other Standard Identifier [v024sa]
	OtherStandardIdentifiers []SearchBibs200ResponseBibRecordsInnerIdentifierOtherStandardIdentifiersInner `json:"otherStandardIdentifiers,omitempty"`
	// Digital Object Identifier [v901sb v024sa]
	Dois []string `json:"dois,omitempty"`
	// Merged OCLC numbers [v019sa]
	MergedOclcNumbers []string `json:"mergedOclcNumbers,omitempty"`
	// GPO Item number [v074sa]
	GpoNumber []string `json:"gpoNumber,omitempty"`
}

// NewSearchBibs200ResponseBibRecordsInnerIdentifier instantiates a new SearchBibs200ResponseBibRecordsInnerIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBibs200ResponseBibRecordsInnerIdentifier() *SearchBibs200ResponseBibRecordsInnerIdentifier {
	this := SearchBibs200ResponseBibRecordsInnerIdentifier{}
	return &this
}

// NewSearchBibs200ResponseBibRecordsInnerIdentifierWithDefaults instantiates a new SearchBibs200ResponseBibRecordsInnerIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBibs200ResponseBibRecordsInnerIdentifierWithDefaults() *SearchBibs200ResponseBibRecordsInnerIdentifier {
	this := SearchBibs200ResponseBibRecordsInnerIdentifier{}
	return &this
}

// GetOclcNumber returns the OclcNumber field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetOclcNumber() int64 {
	if o == nil || IsNil(o.OclcNumber) {
		var ret int64
		return ret
	}
	return *o.OclcNumber
}

// GetOclcNumberOk returns a tuple with the OclcNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetOclcNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.OclcNumber) {
		return nil, false
	}
	return o.OclcNumber, true
}

// HasOclcNumber returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasOclcNumber() bool {
	if o != nil && !IsNil(o.OclcNumber) {
		return true
	}

	return false
}

// SetOclcNumber gets a reference to the given int64 and assigns it to the OclcNumber field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetOclcNumber(v int64) {
	o.OclcNumber = &v
}

// GetLccn returns the Lccn field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetLccn() string {
	if o == nil || IsNil(o.Lccn) {
		var ret string
		return ret
	}
	return *o.Lccn
}

// GetLccnOk returns a tuple with the Lccn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetLccnOk() (*string, bool) {
	if o == nil || IsNil(o.Lccn) {
		return nil, false
	}
	return o.Lccn, true
}

// HasLccn returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasLccn() bool {
	if o != nil && !IsNil(o.Lccn) {
		return true
	}

	return false
}

// SetLccn gets a reference to the given string and assigns it to the Lccn field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetLccn(v string) {
	o.Lccn = &v
}

// GetIsbns returns the Isbns field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetIsbns() []string {
	if o == nil || IsNil(o.Isbns) {
		var ret []string
		return ret
	}
	return o.Isbns
}

// GetIsbnsOk returns a tuple with the Isbns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetIsbnsOk() ([]string, bool) {
	if o == nil || IsNil(o.Isbns) {
		return nil, false
	}
	return o.Isbns, true
}

// HasIsbns returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasIsbns() bool {
	if o != nil && !IsNil(o.Isbns) {
		return true
	}

	return false
}

// SetIsbns gets a reference to the given []string and assigns it to the Isbns field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetIsbns(v []string) {
	o.Isbns = v
}

// GetIssns returns the Issns field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetIssns() []string {
	if o == nil || IsNil(o.Issns) {
		var ret []string
		return ret
	}
	return o.Issns
}

// GetIssnsOk returns a tuple with the Issns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetIssnsOk() ([]string, bool) {
	if o == nil || IsNil(o.Issns) {
		return nil, false
	}
	return o.Issns, true
}

// HasIssns returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasIssns() bool {
	if o != nil && !IsNil(o.Issns) {
		return true
	}

	return false
}

// SetIssns gets a reference to the given []string and assigns it to the Issns field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetIssns(v []string) {
	o.Issns = v
}

// GetExternalIdentifiers returns the ExternalIdentifiers field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetExternalIdentifiers() []SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner {
	if o == nil || IsNil(o.ExternalIdentifiers) {
		var ret []SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner
		return ret
	}
	return o.ExternalIdentifiers
}

// GetExternalIdentifiersOk returns a tuple with the ExternalIdentifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetExternalIdentifiersOk() ([]SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner, bool) {
	if o == nil || IsNil(o.ExternalIdentifiers) {
		return nil, false
	}
	return o.ExternalIdentifiers, true
}

// HasExternalIdentifiers returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasExternalIdentifiers() bool {
	if o != nil && !IsNil(o.ExternalIdentifiers) {
		return true
	}

	return false
}

// SetExternalIdentifiers gets a reference to the given []SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner and assigns it to the ExternalIdentifiers field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetExternalIdentifiers(v []SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) {
	o.ExternalIdentifiers = v
}

// GetOtherStandardIdentifiers returns the OtherStandardIdentifiers field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetOtherStandardIdentifiers() []SearchBibs200ResponseBibRecordsInnerIdentifierOtherStandardIdentifiersInner {
	if o == nil || IsNil(o.OtherStandardIdentifiers) {
		var ret []SearchBibs200ResponseBibRecordsInnerIdentifierOtherStandardIdentifiersInner
		return ret
	}
	return o.OtherStandardIdentifiers
}

// GetOtherStandardIdentifiersOk returns a tuple with the OtherStandardIdentifiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetOtherStandardIdentifiersOk() ([]SearchBibs200ResponseBibRecordsInnerIdentifierOtherStandardIdentifiersInner, bool) {
	if o == nil || IsNil(o.OtherStandardIdentifiers) {
		return nil, false
	}
	return o.OtherStandardIdentifiers, true
}

// HasOtherStandardIdentifiers returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasOtherStandardIdentifiers() bool {
	if o != nil && !IsNil(o.OtherStandardIdentifiers) {
		return true
	}

	return false
}

// SetOtherStandardIdentifiers gets a reference to the given []SearchBibs200ResponseBibRecordsInnerIdentifierOtherStandardIdentifiersInner and assigns it to the OtherStandardIdentifiers field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetOtherStandardIdentifiers(v []SearchBibs200ResponseBibRecordsInnerIdentifierOtherStandardIdentifiersInner) {
	o.OtherStandardIdentifiers = v
}

// GetDois returns the Dois field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetDois() []string {
	if o == nil || IsNil(o.Dois) {
		var ret []string
		return ret
	}
	return o.Dois
}

// GetDoisOk returns a tuple with the Dois field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetDoisOk() ([]string, bool) {
	if o == nil || IsNil(o.Dois) {
		return nil, false
	}
	return o.Dois, true
}

// HasDois returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasDois() bool {
	if o != nil && !IsNil(o.Dois) {
		return true
	}

	return false
}

// SetDois gets a reference to the given []string and assigns it to the Dois field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetDois(v []string) {
	o.Dois = v
}

// GetMergedOclcNumbers returns the MergedOclcNumbers field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetMergedOclcNumbers() []string {
	if o == nil || IsNil(o.MergedOclcNumbers) {
		var ret []string
		return ret
	}
	return o.MergedOclcNumbers
}

// GetMergedOclcNumbersOk returns a tuple with the MergedOclcNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetMergedOclcNumbersOk() ([]string, bool) {
	if o == nil || IsNil(o.MergedOclcNumbers) {
		return nil, false
	}
	return o.MergedOclcNumbers, true
}

// HasMergedOclcNumbers returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasMergedOclcNumbers() bool {
	if o != nil && !IsNil(o.MergedOclcNumbers) {
		return true
	}

	return false
}

// SetMergedOclcNumbers gets a reference to the given []string and assigns it to the MergedOclcNumbers field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetMergedOclcNumbers(v []string) {
	o.MergedOclcNumbers = v
}

// GetGpoNumber returns the GpoNumber field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetGpoNumber() []string {
	if o == nil || IsNil(o.GpoNumber) {
		var ret []string
		return ret
	}
	return o.GpoNumber
}

// GetGpoNumberOk returns a tuple with the GpoNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) GetGpoNumberOk() ([]string, bool) {
	if o == nil || IsNil(o.GpoNumber) {
		return nil, false
	}
	return o.GpoNumber, true
}

// HasGpoNumber returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) HasGpoNumber() bool {
	if o != nil && !IsNil(o.GpoNumber) {
		return true
	}

	return false
}

// SetGpoNumber gets a reference to the given []string and assigns it to the GpoNumber field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifier) SetGpoNumber(v []string) {
	o.GpoNumber = v
}

func (o SearchBibs200ResponseBibRecordsInnerIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBibs200ResponseBibRecordsInnerIdentifier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OclcNumber) {
		toSerialize["oclcNumber"] = o.OclcNumber
	}
	if !IsNil(o.Lccn) {
		toSerialize["lccn"] = o.Lccn
	}
	if !IsNil(o.Isbns) {
		toSerialize["isbns"] = o.Isbns
	}
	if !IsNil(o.Issns) {
		toSerialize["issns"] = o.Issns
	}
	if !IsNil(o.ExternalIdentifiers) {
		toSerialize["externalIdentifiers"] = o.ExternalIdentifiers
	}
	if !IsNil(o.OtherStandardIdentifiers) {
		toSerialize["otherStandardIdentifiers"] = o.OtherStandardIdentifiers
	}
	if !IsNil(o.Dois) {
		toSerialize["dois"] = o.Dois
	}
	if !IsNil(o.MergedOclcNumbers) {
		toSerialize["mergedOclcNumbers"] = o.MergedOclcNumbers
	}
	if !IsNil(o.GpoNumber) {
		toSerialize["gpoNumber"] = o.GpoNumber
	}
	return toSerialize, nil
}

type NullableSearchBibs200ResponseBibRecordsInnerIdentifier struct {
	value *SearchBibs200ResponseBibRecordsInnerIdentifier
	isSet bool
}

func (v NullableSearchBibs200ResponseBibRecordsInnerIdentifier) Get() *SearchBibs200ResponseBibRecordsInnerIdentifier {
	return v.value
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerIdentifier) Set(val *SearchBibs200ResponseBibRecordsInnerIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBibs200ResponseBibRecordsInnerIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBibs200ResponseBibRecordsInnerIdentifier(val *SearchBibs200ResponseBibRecordsInnerIdentifier) *NullableSearchBibs200ResponseBibRecordsInnerIdentifier {
	return &NullableSearchBibs200ResponseBibRecordsInnerIdentifier{value: val, isSet: true}
}

func (v NullableSearchBibs200ResponseBibRecordsInnerIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
