/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner{}

// SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner struct for SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner
type SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner struct {
	OclcSymbol          *string `json:"oclcSymbol,omitempty"`
	SystemControlNumber *string `json:"systemControlNumber,omitempty"`
	OaiSetName          *string `json:"oaiSetName,omitempty"`
	ContentTypeId       *string `json:"contentTypeId,omitempty"`
}

// NewSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner instantiates a new SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner() *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner {
	this := SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner{}
	return &this
}

// NewSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInnerWithDefaults instantiates a new SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInnerWithDefaults() *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner {
	this := SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner{}
	return &this
}

// GetOclcSymbol returns the OclcSymbol field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetOclcSymbol() string {
	if o == nil || IsNil(o.OclcSymbol) {
		var ret string
		return ret
	}
	return *o.OclcSymbol
}

// GetOclcSymbolOk returns a tuple with the OclcSymbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetOclcSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.OclcSymbol) {
		return nil, false
	}
	return o.OclcSymbol, true
}

// HasOclcSymbol returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) HasOclcSymbol() bool {
	if o != nil && !IsNil(o.OclcSymbol) {
		return true
	}

	return false
}

// SetOclcSymbol gets a reference to the given string and assigns it to the OclcSymbol field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) SetOclcSymbol(v string) {
	o.OclcSymbol = &v
}

// GetSystemControlNumber returns the SystemControlNumber field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetSystemControlNumber() string {
	if o == nil || IsNil(o.SystemControlNumber) {
		var ret string
		return ret
	}
	return *o.SystemControlNumber
}

// GetSystemControlNumberOk returns a tuple with the SystemControlNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetSystemControlNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SystemControlNumber) {
		return nil, false
	}
	return o.SystemControlNumber, true
}

// HasSystemControlNumber returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) HasSystemControlNumber() bool {
	if o != nil && !IsNil(o.SystemControlNumber) {
		return true
	}

	return false
}

// SetSystemControlNumber gets a reference to the given string and assigns it to the SystemControlNumber field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) SetSystemControlNumber(v string) {
	o.SystemControlNumber = &v
}

// GetOaiSetName returns the OaiSetName field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetOaiSetName() string {
	if o == nil || IsNil(o.OaiSetName) {
		var ret string
		return ret
	}
	return *o.OaiSetName
}

// GetOaiSetNameOk returns a tuple with the OaiSetName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetOaiSetNameOk() (*string, bool) {
	if o == nil || IsNil(o.OaiSetName) {
		return nil, false
	}
	return o.OaiSetName, true
}

// HasOaiSetName returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) HasOaiSetName() bool {
	if o != nil && !IsNil(o.OaiSetName) {
		return true
	}

	return false
}

// SetOaiSetName gets a reference to the given string and assigns it to the OaiSetName field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) SetOaiSetName(v string) {
	o.OaiSetName = &v
}

// GetContentTypeId returns the ContentTypeId field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetContentTypeId() string {
	if o == nil || IsNil(o.ContentTypeId) {
		var ret string
		return ret
	}
	return *o.ContentTypeId
}

// GetContentTypeIdOk returns a tuple with the ContentTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) GetContentTypeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContentTypeId) {
		return nil, false
	}
	return o.ContentTypeId, true
}

// HasContentTypeId returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) HasContentTypeId() bool {
	if o != nil && !IsNil(o.ContentTypeId) {
		return true
	}

	return false
}

// SetContentTypeId gets a reference to the given string and assigns it to the ContentTypeId field.
func (o *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) SetContentTypeId(v string) {
	o.ContentTypeId = &v
}

func (o SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OclcSymbol) {
		toSerialize["oclcSymbol"] = o.OclcSymbol
	}
	if !IsNil(o.SystemControlNumber) {
		toSerialize["systemControlNumber"] = o.SystemControlNumber
	}
	if !IsNil(o.OaiSetName) {
		toSerialize["oaiSetName"] = o.OaiSetName
	}
	if !IsNil(o.ContentTypeId) {
		toSerialize["contentTypeId"] = o.ContentTypeId
	}
	return toSerialize, nil
}

type NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner struct {
	value *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner
	isSet bool
}

func (v NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) Get() *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner {
	return v.value
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) Set(val *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner(val *SearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) *NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner {
	return &NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner{value: val, isSet: true}
}

func (v NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerIdentifierExternalIdentifiersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
