/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber{}

// FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber Local call number [LHR -> v852sh,i,j,k,l,m]
type FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber struct {
	// Display call Number [LHR -> v852 |k,h,i,m / |j/ |l]
	DisplayCallNumber *string `json:"displayCallNumber,omitempty"`
	// LHR -> v852sh
	ClassificationPart *string `json:"classificationPart,omitempty"`
	// LHR -> v852si
	ItemParts []string `json:"itemParts,omitempty"`
	// LHR -> v852sj
	ShelvingControlNumber *string `json:"shelvingControlNumber,omitempty"`
	// LHR -> v852sk
	Prefixes []string `json:"prefixes,omitempty"`
	// LHR -> v852sl
	ShelvingForm *string `json:"shelvingForm,omitempty"`
	// LHR -> v852sm
	Suffixes []string `json:"suffixes,omitempty"`
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber{}
	return &this
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumberWithDefaults instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumberWithDefaults() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber{}
	return &this
}

// GetDisplayCallNumber returns the DisplayCallNumber field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetDisplayCallNumber() string {
	if o == nil || IsNil(o.DisplayCallNumber) {
		var ret string
		return ret
	}
	return *o.DisplayCallNumber
}

// GetDisplayCallNumberOk returns a tuple with the DisplayCallNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetDisplayCallNumberOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayCallNumber) {
		return nil, false
	}
	return o.DisplayCallNumber, true
}

// HasDisplayCallNumber returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) HasDisplayCallNumber() bool {
	if o != nil && !IsNil(o.DisplayCallNumber) {
		return true
	}

	return false
}

// SetDisplayCallNumber gets a reference to the given string and assigns it to the DisplayCallNumber field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) SetDisplayCallNumber(v string) {
	o.DisplayCallNumber = &v
}

// GetClassificationPart returns the ClassificationPart field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetClassificationPart() string {
	if o == nil || IsNil(o.ClassificationPart) {
		var ret string
		return ret
	}
	return *o.ClassificationPart
}

// GetClassificationPartOk returns a tuple with the ClassificationPart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetClassificationPartOk() (*string, bool) {
	if o == nil || IsNil(o.ClassificationPart) {
		return nil, false
	}
	return o.ClassificationPart, true
}

// HasClassificationPart returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) HasClassificationPart() bool {
	if o != nil && !IsNil(o.ClassificationPart) {
		return true
	}

	return false
}

// SetClassificationPart gets a reference to the given string and assigns it to the ClassificationPart field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) SetClassificationPart(v string) {
	o.ClassificationPart = &v
}

// GetItemParts returns the ItemParts field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetItemParts() []string {
	if o == nil || IsNil(o.ItemParts) {
		var ret []string
		return ret
	}
	return o.ItemParts
}

// GetItemPartsOk returns a tuple with the ItemParts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetItemPartsOk() ([]string, bool) {
	if o == nil || IsNil(o.ItemParts) {
		return nil, false
	}
	return o.ItemParts, true
}

// HasItemParts returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) HasItemParts() bool {
	if o != nil && !IsNil(o.ItemParts) {
		return true
	}

	return false
}

// SetItemParts gets a reference to the given []string and assigns it to the ItemParts field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) SetItemParts(v []string) {
	o.ItemParts = v
}

// GetShelvingControlNumber returns the ShelvingControlNumber field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetShelvingControlNumber() string {
	if o == nil || IsNil(o.ShelvingControlNumber) {
		var ret string
		return ret
	}
	return *o.ShelvingControlNumber
}

// GetShelvingControlNumberOk returns a tuple with the ShelvingControlNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetShelvingControlNumberOk() (*string, bool) {
	if o == nil || IsNil(o.ShelvingControlNumber) {
		return nil, false
	}
	return o.ShelvingControlNumber, true
}

// HasShelvingControlNumber returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) HasShelvingControlNumber() bool {
	if o != nil && !IsNil(o.ShelvingControlNumber) {
		return true
	}

	return false
}

// SetShelvingControlNumber gets a reference to the given string and assigns it to the ShelvingControlNumber field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) SetShelvingControlNumber(v string) {
	o.ShelvingControlNumber = &v
}

// GetPrefixes returns the Prefixes field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetPrefixes() []string {
	if o == nil || IsNil(o.Prefixes) {
		var ret []string
		return ret
	}
	return o.Prefixes
}

// GetPrefixesOk returns a tuple with the Prefixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetPrefixesOk() ([]string, bool) {
	if o == nil || IsNil(o.Prefixes) {
		return nil, false
	}
	return o.Prefixes, true
}

// HasPrefixes returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) HasPrefixes() bool {
	if o != nil && !IsNil(o.Prefixes) {
		return true
	}

	return false
}

// SetPrefixes gets a reference to the given []string and assigns it to the Prefixes field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) SetPrefixes(v []string) {
	o.Prefixes = v
}

// GetShelvingForm returns the ShelvingForm field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetShelvingForm() string {
	if o == nil || IsNil(o.ShelvingForm) {
		var ret string
		return ret
	}
	return *o.ShelvingForm
}

// GetShelvingFormOk returns a tuple with the ShelvingForm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetShelvingFormOk() (*string, bool) {
	if o == nil || IsNil(o.ShelvingForm) {
		return nil, false
	}
	return o.ShelvingForm, true
}

// HasShelvingForm returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) HasShelvingForm() bool {
	if o != nil && !IsNil(o.ShelvingForm) {
		return true
	}

	return false
}

// SetShelvingForm gets a reference to the given string and assigns it to the ShelvingForm field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) SetShelvingForm(v string) {
	o.ShelvingForm = &v
}

// GetSuffixes returns the Suffixes field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetSuffixes() []string {
	if o == nil || IsNil(o.Suffixes) {
		var ret []string
		return ret
	}
	return o.Suffixes
}

// GetSuffixesOk returns a tuple with the Suffixes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) GetSuffixesOk() ([]string, bool) {
	if o == nil || IsNil(o.Suffixes) {
		return nil, false
	}
	return o.Suffixes, true
}

// HasSuffixes returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) HasSuffixes() bool {
	if o != nil && !IsNil(o.Suffixes) {
		return true
	}

	return false
}

// SetSuffixes gets a reference to the given []string and assigns it to the Suffixes field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) SetSuffixes(v []string) {
	o.Suffixes = v
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayCallNumber) {
		toSerialize["displayCallNumber"] = o.DisplayCallNumber
	}
	if !IsNil(o.ClassificationPart) {
		toSerialize["classificationPart"] = o.ClassificationPart
	}
	if !IsNil(o.ItemParts) {
		toSerialize["itemParts"] = o.ItemParts
	}
	if !IsNil(o.ShelvingControlNumber) {
		toSerialize["shelvingControlNumber"] = o.ShelvingControlNumber
	}
	if !IsNil(o.Prefixes) {
		toSerialize["prefixes"] = o.Prefixes
	}
	if !IsNil(o.ShelvingForm) {
		toSerialize["shelvingForm"] = o.ShelvingForm
	}
	if !IsNil(o.Suffixes) {
		toSerialize["suffixes"] = o.Suffixes
	}
	return toSerialize, nil
}

type NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber struct {
	value *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber
	isSet bool
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) Get() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber {
	return v.value
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) Set(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber {
	return &NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber{value: val, isSet: true}
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1CallNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
