/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SearchBibs200ResponseBibRecordsInnerDatabase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBibs200ResponseBibRecordsInnerDatabase{}

// SearchBibs200ResponseBibRecordsInnerDatabase struct for SearchBibs200ResponseBibRecordsInnerDatabase
type SearchBibs200ResponseBibRecordsInnerDatabase struct {
	// Source Collection [Admin/SourceCol]
	Source *string `json:"source,omitempty"`
	// Db Collection [root collection attribute]
	Collection *string `json:"collection,omitempty"`
}

// NewSearchBibs200ResponseBibRecordsInnerDatabase instantiates a new SearchBibs200ResponseBibRecordsInnerDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBibs200ResponseBibRecordsInnerDatabase() *SearchBibs200ResponseBibRecordsInnerDatabase {
	this := SearchBibs200ResponseBibRecordsInnerDatabase{}
	return &this
}

// NewSearchBibs200ResponseBibRecordsInnerDatabaseWithDefaults instantiates a new SearchBibs200ResponseBibRecordsInnerDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBibs200ResponseBibRecordsInnerDatabaseWithDefaults() *SearchBibs200ResponseBibRecordsInnerDatabase {
	this := SearchBibs200ResponseBibRecordsInnerDatabase{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) SetSource(v string) {
	o.Source = &v
}

// GetCollection returns the Collection field value if set, zero value otherwise.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) GetCollection() string {
	if o == nil || IsNil(o.Collection) {
		var ret string
		return ret
	}
	return *o.Collection
}

// GetCollectionOk returns a tuple with the Collection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) GetCollectionOk() (*string, bool) {
	if o == nil || IsNil(o.Collection) {
		return nil, false
	}
	return o.Collection, true
}

// HasCollection returns a boolean if a field has been set.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) HasCollection() bool {
	if o != nil && !IsNil(o.Collection) {
		return true
	}

	return false
}

// SetCollection gets a reference to the given string and assigns it to the Collection field.
func (o *SearchBibs200ResponseBibRecordsInnerDatabase) SetCollection(v string) {
	o.Collection = &v
}

func (o SearchBibs200ResponseBibRecordsInnerDatabase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBibs200ResponseBibRecordsInnerDatabase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Collection) {
		toSerialize["collection"] = o.Collection
	}
	return toSerialize, nil
}

type NullableSearchBibs200ResponseBibRecordsInnerDatabase struct {
	value *SearchBibs200ResponseBibRecordsInnerDatabase
	isSet bool
}

func (v NullableSearchBibs200ResponseBibRecordsInnerDatabase) Get() *SearchBibs200ResponseBibRecordsInnerDatabase {
	return v.value
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerDatabase) Set(val *SearchBibs200ResponseBibRecordsInnerDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBibs200ResponseBibRecordsInnerDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBibs200ResponseBibRecordsInnerDatabase(val *SearchBibs200ResponseBibRecordsInnerDatabase) *NullableSearchBibs200ResponseBibRecordsInnerDatabase {
	return &NullableSearchBibs200ResponseBibRecordsInnerDatabase{value: val, isSet: true}
}

func (v NullableSearchBibs200ResponseBibRecordsInnerDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBibs200ResponseBibRecordsInnerDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
