/*
WorldCat Search API v. 2

Searching of WorldCat

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner{}

// FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner struct for FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner
type FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner struct {
	From *string `json:"from,omitempty"`
	To   *string `json:"to,omitempty"`
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner{}
	return &this
}

// NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInnerWithDefaults instantiates a new FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInnerWithDefaults() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner {
	this := FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner{}
	return &this
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) SetTo(v string) {
	o.To = &v
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner struct {
	value *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner
	isSet bool
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) Get() *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner {
	return v.value
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) Set(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner(val *FindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner {
	return &NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner{value: val, isSet: true}
}

func (v NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindBibRetainedHoldings200ResponseBriefRecordsInnerInstitutionHoldingOneOfInner1HoldingPartsInnerYearRangesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
