openapi: 3.0.2
info:
  description: Searching of WorldCat
  title: WorldCat Search API v. 2
  version: 2.0.0
servers:
- url: https://americas.discovery.api.oclc.org/worldcat/search/v2
security:
- worldcat_search_auth:
  - wcapi
paths:
  /bibs-retained-holdings:
    get:
      description: "Given a known item, find the member library holdings with a commitment\
        \ to retain (Shared Print)"
      operationId: find-bib-retained-holdings
      security:
      - worldcat_search_auth:
        - wcapi:view_retained_holdings
      summary: Find member shared print holdings for a known item
      tags:
      - Member Shared Print Holdings
  /bibs-summary-holdings:
    get:
      description: "Given a known item, get summary of holdings"
      operationId: find-bib-summary-holdings
      security:
      - worldcat_search_auth:
        - wcapi:view_summary_holdings
      summary: Get summary of holdings for a known item
      tags:
      - Member General Holdings
  /bibs-holdings:
    get:
      description: "Given a known item, find the member libraries who hold it"
      operationId: find-bib-holdings
      security:
      - worldcat_search_auth:
        - wcapi:view_institution_holdings
      summary: Find member holdings for a known item
      tags:
      - Member General Holdings
  /bibs-detailed-holdings:
    get:
      description: "Given a known item, search member library holdings for detailed\
        \ information"
      operationId: find-bib-detailed-holdings
      security:
      - worldcat_search_auth:
        - wcapi:view_holdings
      summary: Find detailed info of member holdings for a known item
      tags:
      - Member General Holdings
  /bibs:
    get:
      description: "Search Bibliographic Resources. Key Indexes <table cellspacing=\"\
        0\"> <tbody><tr><th>Index Name</th> <th>Index Code</th> </tr> <tr><td>Author</td>\
        \ <td>au</td> </tr><tr><td>Corporate/Conference Name</td> <td>cn</td> </tr><tr><td>ISBN</td>\
        \ <td>bn</td> </tr><tr><td>ISSN</td> <td>in</td> </tr><tr><td>Keyword</td>\
        \ <td>kw</td> </tr><tr><td>LCCN</td> <td>dn</td> </tr><tr><td>Notes</td> <td>nt</td>\
        \ </tr><tr><td>OCLC Number</td> <td>sno</td> </tr><tr><td>Place of publication</td>\
        \ <td>pl</td> </tr><tr><td>Publisher</td> <td>pb</td> </tr><tr><td>Series</td>\
        \ <td>se</td> </tr><tr><td>Standard Number</td> <td>sn</td> </tr><tr><td>Subject</td>\
        \ <td>su</td> </tr><tr><td>Title</td> <td>ti</td> </tr></tbody></table>  \
        \     \n"
      operationId: search-bibs
      security:
      - worldcat_search_auth:
        - wcapi:view_bib
      summary: Search Bibliographic Resources
      tags:
      - Bibliographic Resources
  /bibs/{oclcNumber}:
    get:
      description: Retrieve specific Bibliographic Resource
      operationId: retrieve-bib
      security:
      - worldcat_search_auth:
        - wcapi:view_bib
      summary: Retrieve specific Bibliographic Resource
      tags:
      - Bibliographic Resources
  /brief-bibs:
    get:
      description: "Search Bibliographic Resources. Key Indexes <table cellspacing=\"\
        0\"> <tbody><tr><th>Index Name</th> <th>Index Code</th> </tr> <tr><td>Author</td>\
        \ <td>au</td> </tr><tr><td>Corporate/Conference Name</td> <td>cn</td> </tr><tr><td>ISBN</td>\
        \ <td>bn</td> </tr><tr><td>ISSN</td> <td>in</td> </tr><tr><td>Keyword</td>\
        \ <td>kw</td> </tr><tr><td>LCCN</td> <td>dn</td> </tr><tr><td>Notes</td> <td>nt</td>\
        \ </tr><tr><td>OCLC Number</td> <td>sno</td> </tr><tr><td>Place of publication</td>\
        \ <td>pl</td> </tr><tr><td>Publisher</td> <td>pb</td> </tr><tr><td>Series</td>\
        \ <td>se</td> </tr><tr><td>Standard Number</td> <td>sn</td> </tr><tr><td>Subject</td>\
        \ <td>su</td> </tr><tr><td>Title</td> <td>ti</td> </tr></tbody></table>  \
        \     \n"
      operationId: search-brief-bibs
      security:
      - worldcat_search_auth:
        - wcapi:view_brief_bib
      summary: Search Brief Bibliographic Resources
      tags:
      - Bibliographic Resources
  /brief-bibs/{oclcNumber}:
    get:
      description: Retrieve specific Bibliographic Resource
      operationId: retrieve-brief-bib
      security:
      - worldcat_search_auth:
        - wcapi:view_brief_bib
      summary: Retrieve specific Bibliographic Resource
      tags:
      - Bibliographic Resources
  /brief-bibs/{oclcNumber}/other-editions:
    get:
      description: Retrieve Other Editions related to a particular Bibliographic Resource
      operationId: retrieve-other-editions
      security:
      - worldcat_search_auth:
        - wcapi:view_brief_bib
      summary: Retrieve Other Editions related to a particular Bibliographic Resource
      tags:
      - Bibliographic Resources
  /my-holdings/{controlNumber}:
    get:
      description: Retrieve LHR Resource
      operationId: retrieve-lhr
      security:
      - worldcat_search_auth:
        - wcapi:view_my_holdings
      summary: Retrieve LHR Resource
      tags:
      - Local Holdings Resources
  /my-holdings:
    get:
      description: Search LHR Resources
      operationId: search-lhr
      security:
      - worldcat_search_auth:
        - wcapi:view_my_holdings
      summary: Search LHR Resources
      tags:
      - Local Holdings Resources
  /retained-holdings:
    get:
      description: Search for shared print LHR Resources
      operationId: search-retrained-lhr
      security:
      - worldcat_search_auth:
        - wcapi:view_retained_holdings
      summary: Search for shared print LHR Resources
      tags:
      - Local Holdings Resources
components:
  securitySchemes:
    worldcat_search_auth:
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.oclc.org/auth
          scopes:
            wcapi: perform all the operation in the Discovery domain
            wcapi:view_bib: view bibliographic data
            wcapi:view_brief_bib: view brief bibliographic data
            wcapi:view_retained_holdings: view holdings which libraries have chosen
              to retain
            wcapi:view_summary_holdings: view summary information about library holdings
            wcapi:view_my_holdings: view detailed information about the authentication
              institution's holdings
            wcapi:view_institution_holdings: view information about what library holds
              an item
            wcapi:view_holdings: view detailed information about library holdings
          tokenUrl: https://oauth.oclc.org/token
        clientCredentials:
          scopes:
            wcapi: perform all the operation in the WorldCat Search API
            wcapi:view_bib: view bibliographic data
            wcapi:view_brief_bib: view brief bibliographic data
            wcapi:view_retained_holdings: view holdings which libraries have chosen
              to retain
            wcapi:view_summary_holdings: view summary information about library holdings
            wcapi:view_my_holdings: view detailed information about the authentication
              institution's holdings
            wcapi:view_institution_holdings: view information about what library holds
              an item
            wcapi:view_holdings: view detailed information about library holdings
          tokenUrl: https://oauth.oclc.org/token
      type: oauth2
